### ISSUE TITLE
Move repo into Mozilla GitHub acct

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/FindMyDevice#47]
Let's create a checklist of what needs to be done before we can move this over to **mozilla** or **mozilla-services** GitHub account.

---
- [ ] #79 -- Support l10n (@nchapman)
- [x] Support FXA/oauth (@jrconlin)
- [x] #14 -- Update README.md file with Node.js specific bits
- [x] #25 -- Add some Node.js tests (@nchapman)
- [x] #36 -- Make sure we can deploy minified, static content for front end (@nchapman)
- [x] Merge **new_frontend** branch into **dev** branch
### After move to mozilla repo?
- [ ] OpSec (try yvan and/or psiinon) to review front end code (@nchapman)
- [ ] Go peer code review (@jrconlin)
- [x] Talk to Ops re: staging server setup (JR? -- protip: it isn't benson or gene)
